### ISSUE TITLE
[TES5] Regression: Renaming master files in Plugin headers

### ISSUE THREAD

**Issue by Sharlikran** [wrye-bash/wrye-bash#340]
```Python
Traceback (most recent call last):
  File "bash\balt.py", line 1828, in DoItemMenu
    self.itemMenu.PopupMenu(self,Link.Frame,selected)
  File "bash\balt.py", line 2280, in PopupMenu
    link.AppendToMenu(menu,parent,*args)
  File "bash\balt.py", line 2539, in AppendToMenu
    if not self._append(window): return
  File "bash\basher\misc_links.py", line 293, in _append
    def _append(self, window): return not window.fileInfo.isMod() #--Saves only
AttributeError: 'MasterList' object has no attribute 'fileInfo'
```

From the mods tab when in Skyrim mode and from dev at commit c406b54b49e7e9c0ce1fc59b747ac677c9c1c3f1 you get the following error changing the file name in the list of masters in the header of a plugin.

Git Bisect:

G:\wrye-bash\wrye-bash [(1cc9765...)|BISECTING]> git bisect bad
1cc9765a95ff05ada07781a6bc2bba0a13939424 is the first bad commit
commit 1cc9765a95ff05ada07781a6bc2bba0a13939424
Author: MrD <the.ubik@gmail.com>
Date:   Tue Nov 1 18:55:42 2016 +0200

    Moving ModInfos helpers out of the way:

    And some more renames on fileInfos - we need to be able to tell looking
    at the search results - current situation is suboptimal
    Minimal wrapping - dropped unused parameter since
    ee969ac7b738b1c3219cc20368d6daeda32d9fc1

    Mopy/bash/basher/mod_links.py:
    Renaming private isEsm to differentiate from FileInfos.isEsm()

    Under #336

    Signed-off-by: MrD <the.ubik@gmail.com>

:040000 040000 c26111fafb5efeb62f84e48fdde9e917a7396152 00996cf63892428d0afaa434
f1693dff1206553b M      Mopy
G:\wrye-bash\wrye-bash [(1cc9765...)|BISECTING]>

**Comment by Sharlikran** [comment]
Doesn't work on save games either.

**Comment by Sharlikran** [comment]
I'd really prefer to use the tracker so others can refer to it.  Is that okay?  If not I will PM the next one I'm working on.

**Comment by Sharlikran** [comment]
> Incidentally that's what this commit was about - fileInfo, what's that

If you are asking me I don't know.  You could try to link the code but since I didn't make it, then I probably can't help.

**Comment by Utumno** [comment]
No I am not asking you haha - I meant that it's not a clear name and here we are - it blew in some remote code part.

Yes please pm me - will fix in dev first thing tomorrow.

As a general rule regressions take highest priority - the fix should be as near as possible as the regression

**Comment by Sharlikran** [comment]
okay no problem I PMed you as requested.  I am hoping to see any bugs or regression fixes in dev that I find and then I'm going to try to test utumno-wip the same with with git bisect and all.  I just want to make sure I don't have any odd bugs from dev getting in the way.
