### ISSUE TITLE
Rework internal image API to account for change of size icons (and general maintainability)

### ISSUE THREAD

**Issue by Utumno** [wrye-bash/wrye-bash#366]
We need a well documented and robust internal Image handling API - the tip of the iceberg is the crash reported in http://forums.bethsoft.com/topic/1615914-wrye-bash-thread-114/page-3#entry25316850

> Issue: Changing Windows Desktop properties for larger font size causes issue
>  
> Method for Windows 7: Right click on Desktop -> Personalize -> Choose Display in lower left -> Select Medium 125% click Apply NOTE REQUIRES USER LOG OFF

Traceback from e9b100e68d737e5f5a5a132db64f98a9333a8dc8:
```
Wrye Bash starting
Using Wrye Bash Version 307
OS info: Windows-7-6.1.7601-SP1
Python version: 2.7.10
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: UTF8; output encoding: None; locale: ('en_US', 'cp1252')
filesystem encoding: mbcs
Searching for game to manage:
bush.py   70 _supportedGames: Detected the following supported games via Windows Registry:
bush.py   72 _supportedGames:  oblivion: G:\Games\steamapps\common\Oblivion
bush.py   72 _supportedGames:  skyrim: F:\Games\steamapps\common\Skyrim
bush.py   72 _supportedGames:  skyrim special edition: F:\Games\steamapps\common\Skyrim Special Edition
bush.py   72 _supportedGames:  fallout4: C:\Games\steamapps\common\Fallout 4
bush.py  130 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  136 _detectGames: Set game mode to skyrim found in parent directory of Mopy:  F:\Games\steamapps\common\Skyrim
bush.py  171 setGame: No preferred game specified.
bush.py  151 __setGame:  Using skyrim game: F:\Games\steamapps\common\Skyrim
testing UAC
mods_metadata.py  224 __init__: Using LOOT API version: 0.10.2
__init__.py 4070 InitData: Bsas: bass cannons of skyrim.bsa, Dragonborn.bsa, Skyrim - VoicesExtra.bsa, Skyrim - Textures.bsa, Dawnguard.bsa, HearthFires.bsa, Skyrim - Voices.bsa, Executor.bsa, Skyrim - Interface.bsa, Update.bsa, Skyrim - Animations.bsa, Skyrim - Misc.bsa, Skyrim - Shaders.bsa, Skyrim - Sounds.bsa, Skyrim - Meshes.bsa
__init__.py 4073 InitData: Corrupted bsas: None
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 442, in main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4035, in Init
    frame = BashFrame() # Link.Frame global set here
  File "bash\basher\__init__.py", line 3672, in __init__
    self.SetStatusBar(BashStatusBar(self))
  File "bash\balt.py", line 2896, in __init__
    self.UpdateIconSizes()
  File "bash\basher\__init__.py", line 3560, in UpdateIconSizes
    self._addButton(link)
  File "bash\balt.py", line 2911, in _addButton
    gButton = link.GetBitmapButton(self, style=wx.NO_BORDER)
  File "bash\basher\app_buttons.py", line 194, in GetBitmapButton
    image=self.images[idex].GetBitmap())
  File "bash\basher\app_buttons.py", line 73, in GetBitmapButton
    image = kwdargs.pop('image', None) or balt.images[self.imageKey %
AttributeError: 'App_Button' object has no attribute 'imageKey'
```
However in the bad's commit (2fab6936fcb5c8db03831811c05b20e57ef59204) parent (bisect in the post above by @Sharlikran) we have
![2fab6936fcb5c8db03831811c05b20e57ef59204 306 - parent of bad commit](https://cloud.githubusercontent.com/assets/1365079/23096691/f4223db0-f621-11e6-9dd1-f0478742b647.jpg)

So no icon is there for the custom shortcut and also _Wrye Bash title bar displays a generic application icon_ (many other dialogs are broken too, for instance the BP one displays no icon). So we need an icon/image API. Monkey patched the crash but will have to finally provide an API - already mentioned since forever in #190.

More:

-  badIcons are one size (16) fits all: `badIcons = [Image(bass.dirs['images'].join(u'x.png'))] * 3`
- the code for getting the icon of a file type does not work for many filetypes ` see _get_default_app_icon`:
  - [[python-win32] Getting the associated icon of a file type](https://mail.python.org/pipermail/python-win32/2003-August/001211.html)
  - [Get Associated Filetype Icon for a File](http://stackoverflow.com/q/25511706/281545)
  - [[python-win32] Extract icon from exe files](https://mail.python.org/pipermail/python-win32/2009-April/thread.html#9062) - also https://mail.python.org/pipermail/python-win32/2009-May/thread.html#9094
- ~~icons are not properly centered - seen clearly when hitting alt tab having set windows resolution to %125~~ -> windows issue on the classic themes, occur with most of my applications

We need:

- [ ] investigate the SHGetFileInfo API to get the filetype icons instead of our registry hacks
- [x] probably rebudle our icons including all needed sizes and resolutions -> Let's use SVGs instead, has tons of benefits: #557
- [x] cleanup unused images and update the relevant dict in `bash/__init__.py` -> 93d130c4488c21ceb49c45efe93e363ba84598f7

Links:

- http://nedbatchelder.com/blog/200501/nice_windows_icons_with_wxpython.html (does not seem to do it)
- http://wxpython-users.1045709.n5.nabble.com/wxGTK-task-bar-icon-size-td2353237.html (compare icon bundle with AddIcon - transparency ?)

wx.Image
https://wxpython.org/docs/api/wx.Image-class.html
WorkingWithImages - wxPyWiki
https://wiki.wxpython.org/WorkingWithImages#Conversions_Between_wx.Image.2C_wx.Bitmap.2C_wx.Cursor.2C_wx.Icon_and_String_Data
wx.Icon — wxPython Phoenix 3.0.3 documentation
https://wxpython.org/Phoenix/docs/html/wx.Icon.html
wx.IconBundle — wxPython v2.8.9.1 documentation
http://xoomer.virgilio.it/infinity77/wxPython/Widgets/wx.IconBundle.html
wxPython: How to Minimize to System Tray | The Mouse Vs. The Python
https://www.blog.pythonlibrary.org/2013/07/12/wxpython-how-to-minimize-to-system-tray/

**Comment by Utumno** [comment]
For some tests exploring win32gui.ExtractIcon APIs see: https://github.com/wrye-bash/test_bash/commit/a79e9f87c273216ce1

**Comment by Utumno** [comment]
The API work to the backburner for now

**Comment by Utumno** [comment]
See https://github.com/wrye-bash/wrye-bash/compare/c6f8a38761ea43d3daa3f566509ffcf1a3055e44...190-lazy-de-wx

The scaling code needs to be revisited as well as the `_native_widget` overrides (one right way?) but looks like an API

**Comment by Infernio** [comment]
An eventual goal should be to get rid of the thousand tool and game images we bundle too. For user-defined launchers, we need code to read the icon from an executable anyways in case we don't bundle it, so we should just do that always (if it turns out to be too slow, we can cache the extracted icons). Same for game icons, we can extract those from the game executable on the fly. Haven't looked to see if you're doing that yet, but I really want to get rid of those hundreds of stupid icons :P

**Comment by Utumno** [comment]
It depends on whether we want to display the predefined launchers in a settings page even if they do not exist. I'd say that we should:

312:

- add a settings tab page listing all (existing?) `_display_launcher=True` launchers,  with a cli and path edit widget per launcher
- read the ini for predefined launchers but  warn that in 313 will go
  - remove the keys from the ini
- read the App folder and add those  but  warn that in 313 will go

313:

- remove the App foder and ini reading for those
- revisit icons - extract/ cache extracted?
- make images dir a submodule?
- have a fallback (maybe wx does this already)

One intermediate step would be to revisit icon format - what's best here (or rather the one fast/right way)?

**Comment by Infernio** [comment]
I'm still unsure if a settings page or a new tab is the right solution. A new tab might greatly simplify things like adding links to handle modifying launchers, but the GUI idea I have in mind (basically a grid of icons similar to how Windows' desktop displays shortcuts) can't really be implemented on a BashTab right now. Refactoring that seems very infeasible, so maybe a tab where we use the icon in place of the checkboxes would work?

On the other hand, a settings page lets us do whatever GUI we want, but would need much more code to implement links and such if we want them.

For the icon format: ideal would be SVGs of course, but getting those for icons is extremely rare. Failing that, I don't think we should move away from our current PNGs (since they're binary, any change we make besides moving them will bloat our history!).
Once/if we switch to extracting icons from executables, we can also extract multiple sizes (which are present in nearly all executables since Windows also uses the larger icons) and can then use the most appropriate size, downscaling if necessary.

**Comment by Infernio** [comment]
I might try prototyping a new tab for this after we merge the #456 prerequisites.

**Comment by Utumno** [comment]
I think I'd be more for a settings page, as the launcher feature is to me minor and had cost lots and lots (and lots) of maintenance - but yes let's see after we merge the Store and Lazy APIs.

This is an interlude (digression) from the looming ghost of 480 - this has been tagging along for a couple of years and conflicts wildly - it's hard and all the tools I can get I need, but yeah, launchers :P

**Comment by Infernio** [comment]
Well one of the reasons it's kind of minor (to me as well!) is because it's such a pain to add new launchers and make them do different things right now.

If I want to add a new app launcher to WB, I have to create a shortcut.
If I want to sometimes pass a parameter to it, I have to create a second shortcut and edit that shortcut's properties to add the parameter.
Now the two have the same logo, so I have to dig out a custom logo, edit the shortcut again and associate the logo so I can tell the two apart.

Repeat for every single parameter I might want to add - and it gets completely nightmarish if you want to pass *combinations* of parameters.
Compare that to our current LOOT launcher - there's just one launcher and you right click it to toggle stuff. If we could easily facilitate adding custom launcher with stuff like that, it could become much more feasible to launch all your (modding) tools through WB.

I know people have very extensive lists of third-party apps they launch through MO2 and Vortex, so I think launchers probably are a fairly key feature for a lot of people.

**Comment by Infernio** [comment]
`nightly` is broken right now:
```
Traceback (most recent call last):
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bash.py", line 449, in _main
    bashIni, bush_game, game_ini_path = _detect_game(opts, bash_ini_path)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bash.py", line 563, in _detect_game
    bush_game = _import_bush_and_set_game(opts, bashIni)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bash.py", line 594, in _import_bush_and_set_game
    retCode = _select_game_popup(game_infos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bash.py", line 821, in _select_game_popup
    frame = SelectGamePopup(game_infos, retCode.set)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bash.py", line 706, in __init__
    self._game_to_bitmap = {g.unique_display_name: GuiImage.from_path(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/bash.py", line 706, in <dictcomp>
    self._game_to_bitmap = {g.unique_display_name: GuiImage.from_path(
                                                   ^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/gui/images.py", line 90, in from_path
    return _BmpFromPath(img_path, iconSize, img_type, quality)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/infernio/Programming/wrye-bash/Mopy/bash/gui/images.py", line 56, in __init__
    raise ArgumentError(f'Missing resource file: {self._img_path}')
bash.exception.ArgumentError: Missing resource file: games/enderalse_32.png
```

The problem being that the game select popup needs icons, but the global icon dir isn't initialized yet (should mayne also raise a nicer error for this case).

Specifically, `_detect_game` is called on line 449 of bash.py, but `InitImages` is only called on line 484. Not entirely sure how to best fix this.

**Comment by Infernio** [comment]
Nice merge, looks really good.

I need to revive my Nexus branch at some point, now that status bar buttons aren't an actual nightmare to work on anymore :sweat_smile:
